services:
  stalk-be:
    container_name: stalk-be-dev
    build:
      context: ./Stalk_BE
      dockerfile: Dockerfile
    ports:
      - "8082:8081" # 외부:내부 포트
    volumes:
      - ./stalk_BE/src:/app/src
      - ./keys:/keys  
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - GCP_KEY_FILE=/keys/stalkaiproject-812b3a8660a4.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - stalk-dev-net

  stalk-fe:
    container_name: stalk-fe-dev
    build:
      context: ./Stalk_FE
    ports:
      - "3001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - stalk-dev-net

  nginx:
    container_name: nginx-dev
    image: nginx:latest
    ports:
      - "8443:443"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - stalk-fe
    networks:
      - stalk-dev-net

networks:
  stalk-dev-net:
    external: true
