version: '3.8'

services:
  stalk-be:
    container_name: stalk-be-dev
    build:
      context: ./Stalk_BE
      dockerfile: Dockerfile
    ports:
      - "8082:8081"  # 외부:내부 포트
    volumes:
      - ./stalk_BE/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always

  stalk-fe:
    container_name: stalk-fe-dev
    build:
      context: ./Stalk_FE
    ports:
      - "3001:3000"
    volumes:
      - ./Stalk_FE:/app
    restart: always
