version: '3.8'

services:
  stalk-be:
    container_name: stalk-be-prod
    build:
      context: ./Stalk_BE
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./stalk_BE/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always

    stalk-fe:
      container_name: stalk-fe-prod
      build:
        context: ./Stalk_FE
      ports:
        - "3000:3000"
      restart: always