services:
  stalk-be:
    container_name: stalk-be-prod
    build:
      context: ./Stalk_BE
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./stalk_BE/src:/app/src
      - ./keys:/keys  
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - GCP_KEY_FILE=/keys/stalkaiproject-812b3a8660a4.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - stalk-prod-net

  stalk-fe:
    container_name: stalk-fe-prod
    build:
      context: ./Stalk_FE
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - stalk-prod-net

  # docker-compose.prod.yml
  nginx:
    container_name: nginx-prod
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - stalk-fe
    networks:
      - stalk-prod-net

networks:
  stalk-prod-net:
    external: true
